The-Code-In-Sheep-s-Clothing/bogl

- src/Runtime/Eval.hs
This changes our semantics to call-by-value, as desired in #11
> call-by-value

- package.yaml
- src/Language/Syntax.hs
- src/Runtime/Serializer.hs
- test/Tests.hs
Closes #7 , functionality for JSON serialization. This comes in with the following functions under the new Serializer.hs file, ```encodeGame``` and ```decodeGame```. 
Both are fairly standard, and after looking through quite a lot of documentation I went for using **DeriveDataTypeable** with the **Text.JSON.Generic** import, which allows for automatic encoding/decoding of user-defined types.
The only issue is that the usage of **DeriveDataTypeable** requires an additional language extension to be enabled, marked at the top of both the **Syntax** and **Serializer** files. I don't think this will be a problem, but it will be required for this to work on other platforms as well (mine was tested on mac, assuming it will work on windows as well).
> JSON serialization

- src/API/JSONData.hs
- src/API/RunFileWithCommands.hs
- src/API/SaveFile.hs
- src/API/Server.hs
- src/API/Test.hs
Closes #42 by adding the **/file** endpoint to allow saving of data into **.bgl** files. Endpoint request is as follows.
```json
{
"fileName" : "TestFile",
"content" : "data to write"
}
```
Response format is:
```json
{
"responses": ["TestFile.bgl written successfully"]
}
```
Note that you don't have to add **.bgl** to the end of the file, it's automatically appended. This will also ensure that the only things we can write to are existing or new **.bgl** files, and not anything else by accident.
Also factors out the API into several other files to make it a bit more clear what's going on structurally. I.e. the server is separate from the recognized kinds of JSONData we can take and return, and each endpoint is given it's own file to keep things organized.
> Adds /file to API

- test/Tests.hs
Implementation of tests for CI didn't return a non-zero exit code when the tests failed. This makes a slight change to the main function, so it will properly exit with a failure code if any tests fail or error out.
> Makes Failing Tests Trip CI

- package.yaml
- src/API/CORSMiddleware.hs
- src/API/JSONData.hs
- src/API/ReadFile.hs
- src/API/Server.hs
This is just a last minute addition to the server component. There were CORS (Cross-Origin Resource Sharing) limitations. This adds a middleware that allows these requests to take place from the frontend of a different origin.
I did test this out with the server, and all functions work as expected 👍 . We just need to add the calls and functionality on the front-end and we're good to go.
From the browser results can be seen in the inspector for hitting the run button. Just need a place to put them on the page, and need to clean up the response messages a bit.
Making a request to run commands on examples/TicTacToe.bgl:
Results:
> Adds CORS middleware

- src/API/JSONData.hs
- src/API/RunFileWithCommands.hs
- src/Runtime/Serializer.hs
Fixes encoding functionality so boards are turned in JSON that can be parsed on the frontend. Produces an ```[[Val]]``` making it fairly easy to parse and display as a grid in the Repl feedback.
> Properly encodes board to submit to front-end

- package.yaml
- serverApp/ServerMain.hs
This adds an additional executable that is produced from our build phase, called **spielserver**, and is installed onto the system along with spiel. From here the server can be started easily with ```spielserver``` typed into the terminal.
Combined with the following on the front-end's package.json:
```json
...
"scripts": {
"setup": "git clone https://github.com/The-Code-In-Sheep-s-Clothing/Spiel-Lang.git && cd Spiel-Lang && stack build && stack install",
"start": "spielserver && react-scripts start",
...
```
This creates a one command install from the frontend by typing ```npm run setup```. From there ```npm start``` will start up the server before the frontend goes up. I think this is pretty good for getting close to a 1 click install. We can make it better still, but this means if you …
> Adds server executable as 'spielserver' (WIP)

- release_tools/linux/release.sh
- release_tools/mac/release.sh
- release_tools/windows/release.sh
Adds release tools for mac (a simple build script), along with a working build of **spielserver** that is mac specific. This binary was built on macOS 10.15.3. I tested this specific binary on an old macOS 10.12 Sierra system, and it looks like it worked just fine! 
It still relies on 3 external libs, but they seem to be pretty standard. On top of that getting ghc to actually compile statically is somewhat of a pain, apparently this is a known issue.
Further release tools should be added into respective **windows** and **linux** directories.
> Release Tools for Mac/Linux/Windows and Binaries

- src/Language/Syntax.hs
- src/Parser/Parser.hs
- src/Runtime/Builtins.hs
- src/Runtime/Eval.hs
- src/Typechecker/Typechecker.hs
- test/EvalTests.hs
Martin had mentioned that everything but arithmetic operators should be treated as functions. I removed all non-arithmetic operators that are not in the official syntax, we can define them in the prelude if needed (with the added benefit of allowing students to see how you can build more complicated operators from the basics).
> remove unofficial language features

- serverApp/ServerMain.hs
- src/API/JSONData.hs
- src/API/Run.hs
- src/API/RunCode.hs
- src/API/RunFileWithCommands.hs
- src/API/SaveFile.hs
- src/API/Server.hs
- src/Parser/Parser.hs
This adds a new endpoint `/runCode` to allow running literal BoGL code for a prelude and a game file, without the need to read from a file. 
This uses a lot of the mechanics of the existing `/runCmds` endpoint, and as such it internally generates **tmp_prelude.bgl** and **tmp_tmp.bgl**, files that just created for the purpose of feeding something into the interpreter. I factored out the common functionality between the two into **src/API/Run.hs**, so they both do exactly the same thing once they have files ready to be parsed.
To keep things simple this endpoint uses the exact same format as `/runCmds'. The only difference is that `file` should take the literal game file contents, and `prelude` should take the literal prelude contents; so no file names are passed here. The input and buffer …
> Adds /runCode Endpoint and Port Setting

- src/Parser/Parser.hs
- test/ParserTests.hs
Fixes #76 by adding a little `try` around an attempt to get the name of a declaration part. This allows parsec to soft fail and not consume the characters that caused the error, and another rule can match it instead (or fail).
Test cases have been added for a single board, double board decls (as shown in the issue example) and a bad case is added as well. All tests look good 👍 .
> Fix for Similarly Named Back-to-Back Board Decls

- examples/Prelude.bglp
- src/API/Run.hs
- src/API/RunCode.hs
- src/Parser/Parser.hs
- test/ParserTests.hs
Closes #80. Updates the Parser to allow whitespace before the declarations in the prelude. The declarations themselves already allow whitespace inbetween themselves, but this makes it so comments at the top are valid now.
> Allow Comments at Beginning of Prelude & Parse Code Directly

- src/Parser/Parser.hs
- test/ParserTests.hs
Closes #88, and is mostly some general QOL stuff. Fixes game names so underscores are valid (as they slightly messed up in the last fix). Also adds additional tests to enforce the new adjustments, and reorganizes most existing parser tests by category of test for easier identification later on. A couple other tests were added for edge cases that we weren't sure about in our group to verify they aren't changed later on.
> Tests and Fixes

- src/Parser/Parser.hs
Relatively small PR. Changes 'Gamefile' to 'Code' internally to match with the tab on the frontend. In this way, if parse errors occur they will indicate that they happened in 'Code' now. Closes #96.
> Changes file descriptor of 'gamefile' to 'code'

- examples/ConnectFour.bgl
- src/Runtime/Builtins.hs
- src/Runtime/Eval.hs
This closes #87. It introduces a couple of changes.
- Swaps the bind order of value definitions at runtime, which allows variable equations to properly observe the environment.
- Allows Builtins to report errors if the parameter to their lambdas are not quite right (this in part affected the same issue #87)
This is NOT done. Still needs a patch to Connect4 (which has a typo in it towards the end), and needs to be tested across all examples individually to ensure no subtle bugs are introduced.
> Fixes bind issues and errors for builtins param type mismatch

- src/Language/Syntax.hs
- src/Parser/Parser.hs
- src/Runtime/Eval.hs
- src/Typechecker/Typechecker.hs
- test/ParserTests.hs
This introduces a new Value Definition `TSynVal` to allow for the propagation of Type Synonyms from the prelude to the main gamefile/code. Before type synonyms were recognized only within the context of a given parsec run, and so were lost once parsing of the prelude was done. This allowed for some strange behavior, as documented in #106, where types could not only be redundantly declared in both files, but that there would also be no parse errors for re-declaring a previously used unique name.
> Closes #106, allows type synonyms to propagate from prelude to gamefile

- src/Parser/Parser.hs
- test/ParserTests.hs
As discussed in our past couple meetings, this PR makes `Board` and `Input` optional types in BoGL. Specifically, this PR makes it optional to explicitly define them in the code. If they are not defined, a default type will be supplied (with the implication that Board and Input will be used by instructors only when they are explicitly defined).
The default for `Board` is `type Board = Array(1,1) of Int`.
The default for `Input` is `type Input = Int`.
In addition, this PR makes a slight change to the parser to prevent `Input` from being used on the right hand side of a type synonym. Otherwise such cases as making `type Input = Input` are possible.
> Makes Board & Input optional types, w/ defaults.

- src/Runtime/Eval.hs
- src/Runtime/Values.hs
This closes #111 by allowing value equations to be lazily evaluated at runtime. By doing so, we can insert things like `input` into value equations, and have them properly evaluate at runtime. 
The previous problem was related to how value equations were evaluated *before* the environment was finished setting up. As a result, the fully evaluated value was stored in the environment for every value equation. In contrast, function equations evaluate lazily at runtime, and so they can handle things like input. This change adds ```Pv``` to represent Pending Values to fix this, and is handled similarly to how functions are currently.
> Enable Lazy Evaluation of Value Equations

- examples/Adventure.bgl
- src/Language/Syntax.hs
- src/Parser/Parser.hs
- src/Runtime/Builtins.hs
- src/Runtime/Eval.hs
- src/Typechecker/Typechecker.hs
- test/EvalTests.hs
- test/ParserTests.hs
- test/Utils.hs
Various fixes after the 7/24 meeting, some noted in advance, and some caught while actively working:
- add '/=' expression, and verifies it fails for non-matching types
- fixes '==' to not succeed for non-matching types
- prevents a type syn from being a value of itself or of another type syn in it's enum, i.e. `type A = {A}`
- fixes regression of #104, where type names should not be lower case, adds test against this now
- removes 'next' as a builtin
- adds 'Adventure' to list of example programs, akin to a bare-bones simple command line game.
> Hotfixes, Adds /=, Fixes lowercase typename issue, Removes 'next'

- src/Runtime/Eval.hs
- test/EvalTests.hs
Closes #119 by sanity checking the x and y components of the board index for accessing an element. If the index is out of bounds, an error with a helpful message is reported instead of a crash.
> Report Runtime Error on Invalid Board Index

- src/Parser/Parser.hs
- test/ParserTests.hs
Closes #121 by forcing a lookahead operation in the parsing of identifiers for an initial lowercase character. It seems that before this wasn't an issue, but something has subtly been changed in the parser during a prior patch, and so things need to be watched over carefully. Existing tests look good, and this adds a case that was originally failing beforehand.
> Forces Lowercase Identifiers

- src/Runtime/Eval.hs
- src/Runtime/Monad.hs
- src/Typechecker/Typechecker.hs
- test/ParserTests.hs
- test/Tests.hs
- test/TypeCheckerTests.hs
Closes #110, and closes #102, where bad parameter types could sneak by if symbols were asked for. This is done first by checking to see if the type of the supplied parameter matches the expected input type for a function. If that fails the two are attempted to be unified, and the result is checked back against the expected input type (which should be equivalent now). If the second attempt fails then the typechecker fails with an error. As an example:
```haskell
game Ex
type AB = {A,B}
b : AB -> AB
b(x) = x
```
and in the interpreter you get the following results (one correct, 2 incorrect):
```
> b(A)
A
> b(C)
Type error at: (line 1, column 3) in the Interpreter expression
Could not match types ({C}) and ({A, B}) in expression:
b(C)
> b(1)
Type error at: (line 1, column 3) in the …
```
> Better Param Typechecking

- src/Parser/Parser.hs
- test/EvalTests.hs
- test/ParserTests.hs
This is a quick mid-camp patch to introduce mod as an infix `%`. Before it was present, but as an infix `mod`. This wasn't incorrect in any way, but it was misleading, as it's the only one of the common binary mathematical operators that was not an infix symbol.
> Changes Mod to infix '%'

- src/Typechecker/Monad.hs
- src/Typechecker/Typechecker.hs
- test/TypeCheckerTests.hs
Closes #90, where the type error for an expression that does not match with the type of a board failed with an odd error of `!`. 
This makes a small adjustment by first adding the expression into the state monad, before type checking the expression with the type of the board. By doing so, the previous expression is able to be extracted correctly (whereas before it was missing), and the expected mismatch type error is reported normally.
Additionally, changes the error message for a missing source expression to something a bit more verbose besides `!`. Removes the associated TODO marks, as they were related to this issue before.
> Add Expr for Board Equation into State before TC

- examples/illTyped/badGet.bgl
- examples/illTyped/badIf.bgl
- src/Typechecker/Monad.hs
- src/Typechecker/Typechecker.hs
I have been aware of this for a while, so I finally fixed it with a small patch to prevent someone from running into it before the new type system is implemented.
> disallow ill-typed if and get

- src/Error/Error.hs
- src/Error/TypeError.hs
- src/Language/Syntax.hs
- src/Parser/Parser.hs
- src/Typechecker/Monad.hs
- src/Typechecker/Typechecker.hs
In fixing the issue I introduced in the PR for improving the error structure, I created a partial `cterr` function. While trying to ensure that wouldn't happen again, I realized I introduced compiler warnings so I fixed those too. Finally, I made a one line change to fix a show instance which had an extra space.
> Minor fixes

- stack.yaml
Adds a small section to the `stack.yml` file to include some ghc-options for building with extra warnings and errors. I tested this earlier today by reverting the fix made last night, and could verify I was still getting an incomplete-pattern error for:
- `stack build`
- `stack ghci`
- `stack install`
> Adds GHC Options

- src/Parser/Parser.hs
- test/ParserTests.hs
Closes #103. This PR fixes up a previously observed bug where signatures and equations that did not match names were not caught at the parser level. This resulted in bad error reporting from the type checker instead, and was misleading as it would only trip when the type checker was invoked to verify that value or function equation. An example of an offending statement would be:
```haskell
game Test
b2 : Int -> Int
b(x) = x+1
-- or
b : Int
a = 2
```
These are now both reported correctly as parse errors (Language errors in the online tool), and are caught even if one name is a sub-string of the other name (which was not the case before).
In my local environment, this patch now correctly fails this program to parse no matter what is typed in, and reports:
```
Language Error: "Code" (line 4, …
```
> closes #103, report parse error for mismatched equation names

- src/API/JSONData.hs
- src/API/Run.hs
- src/Parser/Parser.hs
- test/ParserTests.hs
Adds a parameter to the `runCode` api called `programName`, which goes last as a string. Note that this is only the name of the program, not the prelude, which will always be called 'Prelude'. This pairs w/ a 2nd PR in the front-end to work.
> Takes program name as an argument

- src/Runtime/Builtins.hs
- test/EvalTests.hs
- test/TypeCheckerTests.hs
Fixes an observed issue where the `place` function did not verify the position passed was valid. This could lead to an invalid array index hit, which would crash the run and return a haskell error. This was not parsable by the frontend, and result in a obscure 'could not understand your program' error (a fallback error).
This was the same category of error as with the Get operation (ex. `b!(9,9)`). We have an existing check to prevent invalid access there, however that reports a *type error*. For the current implementation of the builtin functions, the parameters are not accessible until evaluation. We do not have an existing `OutOfBounds` error for runtime errors, so I copied over the existing error message here. This should be refined further to address the duplication. We do want this …
> Patch for place bounds check

- src/Runtime/Eval.hs
- src/Runtime/Monad.hs
This closes #159. The issue had nothing to do with the while, but it was easiest to observe the problem there due to the speed at which the environment accumulates. The problem was related to attempting to evaluate function application or references by looking them up in the environment instead first. The environment fills with key:value pairs for all references, functions, and local name bindings via parameters and lets. However, the environment is repeatedly filled with duplicates of all of these upon subsequent evaluations (including repeated function definitions). Normally, this leads to no visible effect due to (from what I can tell) haskell's laziness. The relevant bindings are re-declared fairly close to the front of the list, and a lookup returns very quickly without evaluating …
> Evaluate Apps/Refs from Builtins before Env

- src/Parser/Parser.hs
- src/Utils/String.hs
- test/ParserTests.hs
Closes #163, a reported issue earlier today where a student encountered the following form of parsing bug:
```haskell
game Ex
type Content = {X,O}
f : Context -> Bool
f(X) = if X == O then True else False
```
Pre-patch this generates no parse error, and returns 'False' every time as if it were a constant function. Looking into this I found that the same behavior was also present in function application (would generate a type error instead of a parse error) and the name binding associated with a let expression (which would succeed silently as well). These cases are detailed as:
```haskell
-- bad let
let X = 5 in 5
...
-- bad func app generates a type error instead of a parse error, as no function should start like this
type Content = {X,O}
X(1)
```
This patch introduces a `lookAhead lower` …
> Enforces Lowercase Parameter Names

- src/API/JSONData.hs
- src/API/Run.hs
- src/API/RunCode.hs
- src/Error/Error.hs
- src/Error/TypeError.hs
- src/Language/Types.hs
- src/Parser/Parser.hs
- src/Typechecker/Monad.hs
- src/Typechecker/Typechecker.hs
- src/Utils/General.hs
- test/APITests.hs
- test/ParserTests.hs
- test/Tests.hs
This, in combination with your editor changes, is good to merge so that we have better handling of input for users. Fixes #165.
> Type check input

- src/Error/RuntimeError.hs
- src/Runtime/Eval.hs
- src/Runtime/Monad.hs
- test/EvalTests.hs
- test/ParserTests.hs
- test/Utils.hs
Closes #158. This was reported by Dr. Parham-Mocello earlier today in a different form than previously observed.
This removes the `unpackBool` helper function, and directly changes **if-then-else** and **while** to inspect the results of evaluating their conditions directly. The use of unpack bool was redundant, as there was no reason these functions could not inspect the values themselves. In addition, it discarded the result of anything other than a bool, meaning that runtime errors were discarded as well. This allows the result of the condition to be handled appropriately, and for any errors in either the left or right sub-expressions to be propagated.
Furthermore it was observed that the `evalEq` helper function for the binops **==** and **/=** did not verify that both expressions did …
> Removes unpackBool, BinOps Propagate Errors

- examples/Scope.bgl
- src/Runtime/Eval.hs
- src/Runtime/Monad.hs
- src/Runtime/Values.hs
- test/EvalTests.hs
- test/Tests.hs
Closes #161. Initial workings converting the runtime env to a Map. These changes need scrutinizing:
- Converted the type synonym for `EvalEnv` to a separate data type, with constructors for List and Map based envs respectively.
- Adds `RuntimeEnv` typeclass that describes operations that can be performed on an env
- `insertEvalEnv`
- `extendEvalEnv`
- `unionEvalEnv`
- `lookupEvalEnv`
The base for producing all environments is `emptyEvalEnv`. Changing this changes the base type of the env in all cases.
> Convert EvalEnv from List -> Map

- src/Typechecker/Typechecker.hs
- test/TypeCheckerTests.hs
Updated PR from #172.
Missing test cases, so I'll keep it as a draft for the moment. Didn't add a new type error constructor, just used unknown.
> Match parameter count to input type dimensionality
